# docker-composeのバージョンを指定
version: "3.9"

# db(MySQL),app(Flask)のコンテナを作成
services:
  app:
    # FlaskのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: ./ChatApp/
    # コンテナ名をFlaskに設定
    container_name: Flask
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    volumes:
      - tmp-data:/app/tmp
      - ./ChatApp:/app
      - ./Nginx/static:/app/static

  web:
    container_name: Nginx
    # FlaskのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: ./Nginx/
    volumes:
      - tmp-data:/app/tmp
      - ./Nginx/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  tmp-data:
